# src/pdf_report.py
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from io import BytesIO
import pandas as pd
from typing import Dict, List

def generate_pdf_report(
    filename: Union[str, BytesIO], 
    risk_metrics: pd.DataFrame, 
    monte_carlo_stats: Dict[str, Dict], 
    charts: Dict[str, BytesIO]
):
    """
    Generates a professional risk report PDF.
    
    Args:
        filename (str): Output path for the PDF.
        risk_metrics (pd.DataFrame): Calculated risk metrics.
        monte_carlo_stats (Dict): Dictionary of stats per ticker.
        charts (Dict[str, BytesIO]): Dictionary of chart name -> image buffer.
    """
    doc = SimpleDocTemplate(filename, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = styles['Title']
    heading_style = styles['Heading2']
    normal_style = styles['Normal']
    
    # Title
    story.append(Paragraph("AI Risk Analysis Report", title_style))
    story.append(Spacer(1, 12))
    story.append(Paragraph("Generated by AI Risk Analyzer", normal_style))
    story.append(Spacer(1, 24))
    
    # 1. Executive Summary
    story.append(Paragraph("1. Executive Summary", heading_style))
    story.append(Paragraph(
        "This report provides a comprehensive risk assessment for the selected portfolio. "
        "It includes historical volatility analysis, drawdown evaluation, and Monte Carlo simulations "
        "to project future performance scenarios.",
        normal_style
    ))
    story.append(Spacer(1, 12))
    
    # 2. Risk Metrics Table
    story.append(Paragraph("2. Historical Risk Metrics", heading_style))
    story.append(Spacer(1, 12))
    
    # Convert DataFrame to Table Data
    # Reset index to include Ticker as a column
    metrics_df = risk_metrics.T.reset_index().rename(columns={'index': 'Asset'})
    # Round float values
    mask = metrics_df.select_dtypes(include=['float']).columns
    metrics_df[mask] = metrics_df[mask].apply(lambda x: x.round(4))
    
    table_data = [metrics_df.columns.to_list()] + metrics_df.values.tolist()
    
    t = Table(table_data)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ]))
    story.append(t)
    story.append(Spacer(1, 24))
    
    # 3. Monte Carlo Simulation Results
    story.append(Paragraph("3. Monte Carlo Simulation (Next 1 Year)", heading_style))
    story.append(Spacer(1, 12))
    
    for ticker, stats in monte_carlo_stats.items():
        sub_p = Paragraph(f"<b>{ticker} Projections:</b>", normal_style)
        story.append(sub_p)
        
        # Format stats text
        stats_text = (
            f"Expected Price: {stats['Expected Price']:.2f} | "
            f"Worst Case (5%): {stats['Worst Case (5%)']:.2f} | "
            f"Best Case (95%): {stats['Best Case (95%)']:.2f}"
        )
        story.append(Paragraph(stats_text, normal_style))
        story.append(Spacer(1, 6))
    
    story.append(Spacer(1, 12))

    # 4. Visualizations
    story.append(Paragraph("4. Visualizations", heading_style))
    story.append(Spacer(1, 12))
    
    # Add Price History
    if 'Price History' in charts:
        story.append(Paragraph("Price History", styles['Heading3']))
        story.append(Image(charts['Price History'], width=6*inch, height=4*inch))
        story.append(Spacer(1, 12))
        
    # Add Drawdowns
    if 'Drawdowns' in charts:
        story.append(Paragraph("Historical Drawdowns", styles['Heading3']))
        story.append(Image(charts['Drawdowns'], width=6*inch, height=4*inch))
        story.append(Spacer(1, 12))

    # Add MC Charts
    for name, img_buf in charts.items():
        if name.startswith('MC_'):
            story.append(Paragraph(f"Simulation: {name.replace('MC_', '')}", styles['Heading3']))
            story.append(Image(img_buf, width=6*inch, height=4*inch))
            story.append(Spacer(1, 12))

    # Build PDF
    doc.build(story)
    print(f"PDF Report generated: {filename}")

if __name__ == "__main__":
    # Test would require mock data and valid BytesIO images
    print("PDF Report module loaded.")
